# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='notice.proto',
  package='novel.proto',
  serialized_pb='\n\x0cnotice.proto\x12\x0bnovel.proto\"U\n\x06Notice\x12\x10\n\x08novel_id\x18\x01 \x01(\x0c\x12\x12\n\nchapter_id\x18\x02 \x01(\r\x12\x13\n\x0bupdate_time\x18\x03 \x01(\x04\x12\x10\n\x08\x66inished\x18\x04 \x01(\r')




_NOTICE = descriptor.Descriptor(
  name='Notice',
  full_name='novel.proto.Notice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='novel_id', full_name='novel.proto.Notice.novel_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapter_id', full_name='novel.proto.Notice.chapter_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_time', full_name='novel.proto.Notice.update_time', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='finished', full_name='novel.proto.Notice.finished', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['Notice'] = _NOTICE

class Notice(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTICE
  
  # @@protoc_insertion_point(class_scope:novel.proto.Notice)

# @@protoc_insertion_point(module_scope)
