# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='novel_body.proto',
  package='novel.proto',
  serialized_pb='\n\x10novel_body.proto\x12\x0bnovel.proto\"G\n\x04\x42ody\x12\x10\n\x08novel_id\x18\x01 \x01(\x0c\x12\x12\n\nchapter_id\x18\x02 \x01(\r\x12\x0c\n\x04text\x18\x03 \x01(\x0c\x12\x0b\n\x03url\x18\x04 \x01(\x0c')




_BODY = descriptor.Descriptor(
  name='Body',
  full_name='novel.proto.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='novel_id', full_name='novel.proto.Body.novel_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapter_id', full_name='novel.proto.Body.chapter_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='text', full_name='novel.proto.Body.text', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='novel.proto.Body.url', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['Body'] = _BODY

class Body(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BODY
  
  # @@protoc_insertion_point(class_scope:novel.proto.Body)

# @@protoc_insertion_point(module_scope)
