# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import novel_meta_pb2
import novel_chapter_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='novel.proto',
  package='novel.proto',
  serialized_pb='\n\x0bnovel.proto\x12\x0bnovel.proto\x1a\x10novel_meta.proto\x1a\x13novel_chapter.proto\"\xa8\x01\n\x05Novel\x12\x10\n\x08novel_id\x18\x01 \x01(\x0c\x12$\n\tmain_meta\x18\x02 \x01(\x0b\x32\x11.novel.proto.Meta\x12$\n\thost_meta\x18\x03 \x03(\x0b\x32\x11.novel.proto.Meta\x12&\n\x08\x63hapters\x18\x04 \x03(\x0b\x32\x14.novel.proto.Chapter\x12\x19\n\x11\x63hapter_list_from\x18\x05 \x01(\x0c')




_NOVEL = descriptor.Descriptor(
  name='Novel',
  full_name='novel.proto.Novel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='novel_id', full_name='novel.proto.Novel.novel_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='main_meta', full_name='novel.proto.Novel.main_meta', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host_meta', full_name='novel.proto.Novel.host_meta', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapters', full_name='novel.proto.Novel.chapters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapter_list_from', full_name='novel.proto.Novel.chapter_list_from', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=236,
)

_NOVEL.fields_by_name['main_meta'].message_type = novel_meta_pb2._META
_NOVEL.fields_by_name['host_meta'].message_type = novel_meta_pb2._META
_NOVEL.fields_by_name['chapters'].message_type = novel_chapter_pb2._CHAPTER
DESCRIPTOR.message_types_by_name['Novel'] = _NOVEL

class Novel(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOVEL
  
  # @@protoc_insertion_point(class_scope:novel.proto.Novel)

# @@protoc_insertion_point(module_scope)
