# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='novel_chapter.proto',
  package='novel.proto',
  serialized_pb='\n\x13novel_chapter.proto\x12\x0bnovel.proto\"\xcc\x01\n\x0bHostChapter\x12\x10\n\x08\x62ody_key\x18\x01 \x01(\x0c\x12\x0b\n\x03url\x18\x02 \x01(\x0c\x12\x0c\n\x04host\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63hapter_name\x18\x04 \x01(\x0c\x12\x13\n\x0bupdate_time\x18\x05 \x01(\x04\x12\x12\n\nchapter_id\x18\x06 \x01(\r\x12\x0e\n\x06is_vip\x18\x07 \x01(\r\x12\x15\n\rdiscover_time\x18\x08 \x01(\x04\x12*\n\x06status\x18\t \x01(\x0e\x32\x1a.novel.proto.ChapterStatus\"~\n\x07\x43hapter\x12\x12\n\nchapter_id\x18\x01 \x01(\r\x12.\n\x0cmain_chapter\x18\x03 \x01(\x0b\x32\x18.novel.proto.HostChapter\x12/\n\rhost_chapters\x18\x04 \x03(\x0b\x32\x18.novel.proto.HostChapter*B\n\rChapterStatus\x12\x0f\n\x0bSTATUS_NONE\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x11\n\rSTATUS_FAILED\x10\x02')

_CHAPTERSTATUS = descriptor.EnumDescriptor(
  name='ChapterStatus',
  full_name='novel.proto.ChapterStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='STATUS_NONE', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_OK', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STATUS_FAILED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=371,
  serialized_end=437,
)


STATUS_NONE = 0
STATUS_OK = 1
STATUS_FAILED = 2



_HOSTCHAPTER = descriptor.Descriptor(
  name='HostChapter',
  full_name='novel.proto.HostChapter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='body_key', full_name='novel.proto.HostChapter.body_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='novel.proto.HostChapter.url', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host', full_name='novel.proto.HostChapter.host', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapter_name', full_name='novel.proto.HostChapter.chapter_name', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_time', full_name='novel.proto.HostChapter.update_time', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapter_id', full_name='novel.proto.HostChapter.chapter_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_vip', full_name='novel.proto.HostChapter.is_vip', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='discover_time', full_name='novel.proto.HostChapter.discover_time', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='novel.proto.HostChapter.status', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=241,
)


_CHAPTER = descriptor.Descriptor(
  name='Chapter',
  full_name='novel.proto.Chapter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='chapter_id', full_name='novel.proto.Chapter.chapter_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='main_chapter', full_name='novel.proto.Chapter.main_chapter', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host_chapters', full_name='novel.proto.Chapter.host_chapters', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=243,
  serialized_end=369,
)

_HOSTCHAPTER.fields_by_name['status'].enum_type = _CHAPTERSTATUS
_CHAPTER.fields_by_name['main_chapter'].message_type = _HOSTCHAPTER
_CHAPTER.fields_by_name['host_chapters'].message_type = _HOSTCHAPTER
DESCRIPTOR.message_types_by_name['HostChapter'] = _HOSTCHAPTER
DESCRIPTOR.message_types_by_name['Chapter'] = _CHAPTER

class HostChapter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HOSTCHAPTER
  
  # @@protoc_insertion_point(class_scope:novel.proto.HostChapter)

class Chapter(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHAPTER
  
  # @@protoc_insertion_point(class_scope:novel.proto.Chapter)

# @@protoc_insertion_point(module_scope)
