# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='novel_offline_meta.proto',
  package='midas.cnzz.user_profile',
  serialized_pb='\n\x18novel_offline_meta.proto\x12\x17midas.cnzz.user_profile\"b\n\x10NovelOfflineMeta\x12\x10\n\x08novel_id\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63lick_count\x18\x02 \x01(\r\x12\x12\n\nuser_count\x18\x03 \x01(\r\x12\x13\n\x0bquery_count\x18\x04 \x01(\r')




_NOVELOFFLINEMETA = descriptor.Descriptor(
  name='NovelOfflineMeta',
  full_name='midas.cnzz.user_profile.NovelOfflineMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='novel_id', full_name='midas.cnzz.user_profile.NovelOfflineMeta.novel_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='click_count', full_name='midas.cnzz.user_profile.NovelOfflineMeta.click_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_count', full_name='midas.cnzz.user_profile.NovelOfflineMeta.user_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query_count', full_name='midas.cnzz.user_profile.NovelOfflineMeta.query_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=53,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['NovelOfflineMeta'] = _NOVELOFFLINEMETA

class NovelOfflineMeta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOVELOFFLINEMETA
  
  # @@protoc_insertion_point(class_scope:midas.cnzz.user_profile.NovelOfflineMeta)

# @@protoc_insertion_point(module_scope)
