# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='novel_meta.proto',
  package='novel.proto',
  serialized_pb='\n\x10novel_meta.proto\x12\x0bnovel.proto\"M\n\x0cNovelComment\x12\x16\n\x0e\x63omment_author\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63omment_time\x18\x02 \x01(\x04\x12\x0f\n\x07\x63omment\x18\x03 \x01(\x0c\"\xb8\x05\n\x04Meta\x12\r\n\x05title\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\x0c\x12\x16\n\x0e\x66irst_category\x18\x03 \x01(\x0c\x12\x17\n\x0fsecond_category\x18\x04 \x01(\x0c\x12\x10\n\x08word_num\x18\x05 \x01(\r\x12\x11\n\tclick_num\x18\x06 \x01(\r\x12\x13\n\x0b\x63omment_num\x18\x07 \x01(\r\x12\x14\n\x0c\x66\x61vorite_num\x18\x08 \x01(\r\x12\x10\n\x08\x66inished\x18\t \x01(\r\x12\x13\n\x0b\x63hapter_num\x18\n \x01(\r\x12\x12\n\nstart_time\x18\x0b \x01(\x04\x12\x13\n\x0bupdate_time\x18\x0c \x01(\x04\x12\x14\n\x0cintroduction\x18\r \x01(\x0c\x12\x10\n\x08keywords\x18\x0e \x03(\x0c\x12\x10\n\x08hostname\x18\x0f \x01(\x0c\x12\r\n\x05point\x18\x10 \x01(\r\x12\x15\n\rdiscover_time\x18\x11 \x01(\x04\x12\x31\n\x0enovel_comments\x18\x12 \x03(\x0b\x32\x19.novel.proto.NovelComment\x12\x11\n\ttopic_url\x18\x13 \x01(\x0c\x12\x10\n\x08list_url\x18\x14 \x01(\x0c\x12\x11\n\timage_url\x18\x15 \x01(\x0c\x12\x17\n\x0f\x66irst_published\x18\x16 \x01(\r\x12\x16\n\x0eweek_click_num\x18\x17 \x01(\r\x12\x15\n\rfirst_chapter\x18\x18 \x01(\x0c\x12\x19\n\x11\x66irst_chapter_url\x18\x19 \x01(\x0c\x12\x16\n\x0elatest_chapter\x18\x1a \x01(\x0c\x12\x1a\n\x12latest_chapter_url\x18\x1b \x01(\x0c\x12\x0c\n\x04host\x18\x1c \x01(\x0c\x12\x13\n\x0b\x62ook_number\x18\x1d \x01(\r\x12 \n\x18related_novel_topic_urls\x18\x1e \x03(\x0c\x12\x19\n\x11last_crawled_time\x18\x1f \x01(\x04')




_NOVELCOMMENT = descriptor.Descriptor(
  name='NovelComment',
  full_name='novel.proto.NovelComment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='comment_author', full_name='novel.proto.NovelComment.comment_author', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment_time', full_name='novel.proto.NovelComment.comment_time', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment', full_name='novel.proto.NovelComment.comment', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=110,
)


_META = descriptor.Descriptor(
  name='Meta',
  full_name='novel.proto.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='title', full_name='novel.proto.Meta.title', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='author', full_name='novel.proto.Meta.author', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_category', full_name='novel.proto.Meta.first_category', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='second_category', full_name='novel.proto.Meta.second_category', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='word_num', full_name='novel.proto.Meta.word_num', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='click_num', full_name='novel.proto.Meta.click_num', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='comment_num', full_name='novel.proto.Meta.comment_num', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='favorite_num', full_name='novel.proto.Meta.favorite_num', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='finished', full_name='novel.proto.Meta.finished', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chapter_num', full_name='novel.proto.Meta.chapter_num', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='start_time', full_name='novel.proto.Meta.start_time', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_time', full_name='novel.proto.Meta.update_time', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='introduction', full_name='novel.proto.Meta.introduction', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='keywords', full_name='novel.proto.Meta.keywords', index=13,
      number=14, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hostname', full_name='novel.proto.Meta.hostname', index=14,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='point', full_name='novel.proto.Meta.point', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='discover_time', full_name='novel.proto.Meta.discover_time', index=16,
      number=17, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='novel_comments', full_name='novel.proto.Meta.novel_comments', index=17,
      number=18, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='topic_url', full_name='novel.proto.Meta.topic_url', index=18,
      number=19, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='list_url', full_name='novel.proto.Meta.list_url', index=19,
      number=20, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='image_url', full_name='novel.proto.Meta.image_url', index=20,
      number=21, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_published', full_name='novel.proto.Meta.first_published', index=21,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='week_click_num', full_name='novel.proto.Meta.week_click_num', index=22,
      number=23, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_chapter', full_name='novel.proto.Meta.first_chapter', index=23,
      number=24, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='first_chapter_url', full_name='novel.proto.Meta.first_chapter_url', index=24,
      number=25, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='latest_chapter', full_name='novel.proto.Meta.latest_chapter', index=25,
      number=26, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='latest_chapter_url', full_name='novel.proto.Meta.latest_chapter_url', index=26,
      number=27, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='host', full_name='novel.proto.Meta.host', index=27,
      number=28, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='book_number', full_name='novel.proto.Meta.book_number', index=28,
      number=29, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='related_novel_topic_urls', full_name='novel.proto.Meta.related_novel_topic_urls', index=29,
      number=30, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_crawled_time', full_name='novel.proto.Meta.last_crawled_time', index=30,
      number=31, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=113,
  serialized_end=809,
)

_META.fields_by_name['novel_comments'].message_type = _NOVELCOMMENT
DESCRIPTOR.message_types_by_name['NovelComment'] = _NOVELCOMMENT
DESCRIPTOR.message_types_by_name['Meta'] = _META

class NovelComment(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOVELCOMMENT
  
  # @@protoc_insertion_point(class_scope:novel.proto.NovelComment)

class Meta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _META
  
  # @@protoc_insertion_point(class_scope:novel.proto.Meta)

# @@protoc_insertion_point(module_scope)
